export const ALL_CIRCUIT = 'ALL_CIRCUIT';
export const ALL_CIRCUIT_DETAILS = 'ALL_CIRCUIT_DETAILS';
export const ALL_CIRCUIT_SORT_BY_LOC_ID_ASC = 'ALL_CIRCUIT_SORT_BY_LOC_ID_ASC';
export const ALL_CIRCUIT_SORT_BY_LOC_ID_DES = 'ALL_CIRCUIT_SORT_BY_LOC_ID_DES';
export const ALL_CIRCUIT_SORT_BY_CIR_ID_ASC = 'ALL_CIRCUIT_SORT_BY_CIR_ID_ASC';
export const ALL_CIRCUIT_SORT_BY_CIR_ID_DES = 'ALL_CIRCUIT_SORT_BY_CIR_ID_DES';
export const ALL_CIRCUIT_SORT_BY_BRANCH_ASC =
  'ALL_CIRCUIT_SORT_BY_DEVICE_BRANCH_ASC';
export const ALL_CIRCUIT_SORT_BY_BRANCH_DES =
  'ALL_CIRCUIT_SORT_BY_DEVICE_BRANCH_DES';
export const ALL_CIRCUIT_SORT_BY_VENDOR_ASC = 'ALL_CIRCUIT_SORT_BY_VENDOR_ASC';
export const ALL_CIRCUIT_SORT_BY_VENDOR_DES = 'ALL_CIRCUIT_SORT_BY_VENDOR_DES';
export const ALL_CIRCUIT_FILTER_BY_LOCATION_ID =
  'ALL_CIRCUIT_FILTER_BY_LOCATION_ID';
export const ALL_CIRCUIT_FILTER_BY_CIRCUITS_ID =
  'ALL_CIRCUIT_FILTER_BY_CIRCUITS_ID';
export const ALL_CIRCUIT_FILTER_BY_BRANCH_ID =
  'ALL_CIRCUIT_FILTER_BY_BRANCH_ID';
