export const FILTER_MARKER = 'FILTER_MARKER';
export const CHANGE_BORDER = 'CHANGE_BORDER';
export const CHANGE_BORDER1 = 'CHANGE_BORDER1';
export const CHANGE_BORDER_FILTER = 'CHANGE_BORDER_FILTER';
export const CHANGE_BORDER_BY_LOCATIO_ID = 'CHANGE_BORDER_BY_LOCATIO_ID';
