export const SITE_ID='SITE_ID'
export const SITE_ID_SEARCH='SITE_ID_SEARCH'
export const ATM_ID='ATM_ID'
export const ATM_ID_SEARCH='ATM_ID_SEARCH'
export const BRANCH_ID='BRANCH_ID'
export const BRANCH_ID_SEARCH='BRANCH_ID_SEARCH'
