export const ALL_DEVICES = 'ALL_DEVICE';
export const ALL_DEVICES_DETAILS = 'ALL_DEVICES_DETAILS';
export const ALL_DEVICES_SORT_BY_ID_ASC = 'ALL_DEVICES_SORT_BY_DEVICE_ID_ASC';
export const ALL_DEVICES_SORT_BY_ID_DES = 'ALL_DEVICES_SORT_BY_DEVICE_ID_DES';
export const ALL_DEVICES_SORT_BY_TYPE_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_NAME_ASC';
export const ALL_DEVICES_SORT_BY_TYPE_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_NAME_DES';
export const ALL_DEVICES_SORT_BY_STATUS_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_STATUS_ASC';
export const ALL_DEVICES_SORT_BY_STATUS_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_STATUS_DES';
export const ALL_DEVICES_SORT_BY_VENDOR_ASC =
  'ALL_DEVICES_SORT_BY_DEVICE_VENDOR_ASC';
export const ALL_DEVICES_SORT_BY_VENDOR_DES =
  'ALL_DEVICES_SORT_BY_DEVICE_VENDOR_DES';
